debian/xpm.d/digikam-16.xpm usr/share/pixmaps/
debian/xpm.d/digikam.xpm usr/share/pixmaps/
usr/bin/cleanup_digikamdb
usr/bin/digikam
usr/bin/digitaglinktree
usr/lib/kde4/digikam*
usr/lib/kde4/kio*
usr/lib/kde4/libexec
usr/share/appdata/digiKam-*.metainfo.xml
usr/share/appdata/digikam.appdata.xml
usr/share/applications/kde4/digikam.desktop
usr/share/kde4/apps/kconf_update/
usr/share/man/man1/cleanup_digikamdb.1
usr/share/man/man1/digitaglinktree.1
