usr/share/icons/hicolor/*/apps/digikam.*
usr/share/kde4/apps/d*
usr/share/kde4/apps/solid
usr/share/kde4/services/digikam*
usr/share/kde4/servicetypes/digikamimageplugin.desktop
usr/share/locale/*/LC_MESSAGES/digikam.mo
usr/share/appdata/digiKam-ImagePlugin_Color.metainfo.xml
usr/share/appdata/digiKam-ImagePlugin_Decorate.metainfo.xml
usr/share/appdata/digiKam-ImagePlugin_Enhance.metainfo.xml
usr/share/appdata/digiKam-ImagePlugin_FxFilters.metainfo.xml
usr/share/appdata/digiKam-ImagePlugin_Transform.metainfo.xml
usr/share/appdata/digikam.appdata.xml

