usr/bin/dngconverter
usr/bin/dnginfo
usr/bin/expoblending
usr/bin/panoramagui
usr/bin/photolayoutseditor
usr/bin/scangui
usr/lib/kde4/kipi*
usr/lib/libkipiplugins.so.* usr/lib/digikam/
usr/share/applications/kde4/dngconverter.desktop
usr/share/applications/kde4/expoblending.desktop
usr/share/applications/kde4/kipiplugins.desktop
usr/share/applications/kde4/panoramagui.desktop
usr/share/applications/kde4/photolayoutseditor.desktop
usr/share/applications/kde4/scangui.desktop
usr/share/kde4/config.kcfg/photolayoutseditor.kcfg
usr/share/kde4/services/kipiplugin_*
